### ISSUE TITLE
Clean up code base

### ISSUE THREAD

**Issue by alissayarmantho** [AY2122S1-CS2103T-W11-1/tp#84]
- [x] Make sure address book or description book is gone and change it to inventory/recipe book as appropriate
- [x] Check the returned error messages (eg: missing spaces) that makes the sample command not copy-pastable (add ingredient error message is an example)
- [ ] Rename ingredients commands and parsers to include ingredients and move them to the ingredient folder just like the recipe counterpart
- [ ] Organisation of code (functions related to ingredients should be grouped together with comments to denote the section etc)
- [ ] Some misplaced assertion arguments (should be expected vs actual but it was actual vs expected instead)
- [ ] Optional (Code style refactoring, the test cases have different styles of writing between ingredient and recipes and a mix of here n there, recipe use stubs, ingredients don't, etc)

**Comment by alissayarmantho** [comment]
Closing because the rest are non critical
